compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
    deepspeed_config_file: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-mtai/users/liuqi138/LLaMA-Factory/examples/deepspeed/ds_z00_config.json
    zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: '192.168.0.1'
main_process_port: 29500
main_training_function: main
mixed_precision: fp16
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false